stages:
    - build
build:
    stage: build
    script:
        - export PATH=/opt/instantclient_21_4:/home/gitlab-runner/.nvm/versions/node/v22.13.1/bin:/opt/maven/bin:/opt/jdk/jdk-21.0.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
        - pwd

        - echo "start build image!"
        - docker build -t patblog:latest .

        - echo "kill old container!"
        - docker ps -a -q --filter "name=patblog" | xargs -r docker rm -f

        - echo "start run container!"
        - docker run -d -p 9016:80 --name patblog patblog:latest

        - echo "deploy done!"
        - docker ps -a -f "name=patblog"
        - docker logs patblog
    tags:
        - patblog
    rules:
        - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "demo" 

